export { HomePage } from "./HomePage"
export { AboutPage } from "./AboutPage"
export { ContactPage } from "./ContactPage"
export { ResumePage } from "./ResumePage"
export { CreationsPage } from "./CreationsPage"
